{
 "title": "Analisis Predicciones Clinker",
 "time": { "from": "2010-10-02T14:58:00.000Z", "to": "2010-11-15T12:22:00.000Z" },
 "panels": [
  {
   "title": "Tabla predicción vs real",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Prediccion Cal\", \"% CaO(l)\", \"Calificacion predicha\", \"Calificacion real\" FROM calidad_clinker ORDER BY \"% CaO(l)\" DESC LIMIT 250 "
    }
   ]
  },
  {
   "title": "Cantidad de calificaciones predichas",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Calificacion predicha\", COUNT(\"Prediccion Cal\") FROM calidad_clinker GROUP BY \"Calificacion predicha\" ORDER BY COUNT(\"Prediccion Cal\") ASC LIMIT 250 "
    }
   ]
  },
  {
   "title": "Grafico general",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM calidad_clinker LIMIT 250 "
    }
   ]
  },
  {
   "title": "%CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT fecha_hora, \"% CO2\" FROM calidad_clinker LIMIT 250 "
    }
   ]
  },
  {
   "title": "Resultados predicción vs original del cal libre",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT fecha_hora, \"% CaO(l)\", \"Prediccion Cal\" FROM calidad_clinker LIMIT 250 "
    }
   ]
  },
  {
   "title": "Fase Alita",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT fecha_hora, \"% C3S\" FROM calidad_clinker LIMIT 250 "
    }
   ]
  },
  {
   "title": "Cal libre Promedio/max/min",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"% CaO(l)\"), MAX(\"% CaO(l)\"), MIN(\"% CaO(l)\") FROM calidad_clinker LIMIT 250 "
    }
   ]
  },
  {
   "title": "Fase Ferritoaluminato Tetracálcico.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT fecha_hora, \"% C4AF\" FROM calidad_clinker LIMIT 250 "
    }
   ]
  },
  {
   "title": "Fase Belita, Silicato Dicálcico.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT fecha_hora, \"% C2S\" FROM calidad_clinker LIMIT 250 "
    }
   ]
  },
  {
   "title": "Fase Aluminato Tricálcico.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT fecha_hora, \"% C3A\" FROM calidad_clinker LIMIT 250 "
    }
   ]
  },
  {
   "title": "Cantidad de calificaciones predichas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Calificacion predicha\", COUNT(\"Prediccion Cal\") FROM calidad_clinker GROUP BY \"Calificacion predicha\" ORDER BY COUNT(\"Prediccion Cal\") ASC LIMIT 250 "
    }
   ]
  },
  {
   "title": "Cantidad de calificaciones predichas",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT \"Calificacion predicha\", COUNT(\"Prediccion Cal\") FROM calidad_clinker GROUP BY \"Calificacion predicha\" ORDER BY COUNT(\"Prediccion Cal\") ASC LIMIT 250 "
    }
   ]
  },
  {
   "title": "Cantidad de calificaciones",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Calificacion real\", COUNT(\"% CaO(l)\") FROM calidad_clinker GROUP BY \"Calificacion real\" ORDER BY COUNT(\"% CaO(l)\") ASC LIMIT 250 "
    }
   ]
  },
  {
   "title": "Cantidad de calificaciones",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Calificacion real\", COUNT(\"% CaO(l)\") FROM calidad_clinker GROUP BY \"Calificacion real\" ORDER BY COUNT(\"% CaO(l)\") ASC LIMIT 250 "
    }
   ]
  },
  {
   "title": "Cantidad de calificaciones",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT \"Calificacion real\", COUNT(\"% CaO(l)\") FROM calidad_clinker GROUP BY \"Calificacion real\" ORDER BY COUNT(\"% CaO(l)\") ASC LIMIT 250 "
    }
   ]
  },
  {
   "title": "Prediccion Cal libre Promedio/max/min",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"Prediccion Cal\"), MAX(\"Prediccion Cal\"), MIN(\"Prediccion Cal\") FROM calidad_clinker LIMIT 250 "
    }
   ]
  }
 ]
}